[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "@arianee/=src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
tab_width = 4
max_line_length = 120
multiline_func_header = "params_first"
override_spacing = true
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"

[fuzz]
# runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Some notes for Maxime when adding CI capabilities:
# --fail-fast (Stop running tests after the first failur) can be a good option to add when running tests in CI
# --fuzz-runs (Number of runs for each fuzz test) can be set to a higher number in CI to make sure the tests are more reliable
# -v[vvvv] (Verbose output) can be useful to see more details about the tests in CI