[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings = [
    "@arianee/=src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
tab_width = 4
max_line_length = 120
multiline_func_header = "params_first"
override_spacing = true
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options