version: 2.1

executors:
  foundry-executor:
    docker:
      - image: ghcr.io/foundry-rs/foundry:latest

jobs:
  test:
    executor: foundry-executor
    steps:
      - checkout
      - run:
          name: Install Node and NPM
          command: |
            apk add --update nodejs npm bash
      - run:
          name: Install Node dependencies
          command: npm ci
      - run:
          name: Install Forge dependencies
          command: forge install
      - run:
          name: Install node dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm run test -- --fuzz-runs 1
      - run:
          name: Run tests with prover
          command: npm run test:prover -- --fuzz-runs 1
      - run:
          name: Run lint
          command: forge fmt --check --raw

workflows:
  test:
    jobs:
      - test
