version: 2.1

executors:
  foundry-executor:
    docker:
      - image: ghcr.io/foundry-rs/foundry:latest

jobs:
  test:
    executor: foundry-executor
    steps:
      - checkout
      - run:
          name: Install requirement
          command: |
            apk add --update nodejs npm bash
      - run:
          name: Clean artifacts and cache directories
          command: forge clean
      - run:
          name: Run tests
          command: forge test --fail-fast --fuzz-runs 1000
      - run:
          name: Run lints
          command: forge fmt --check --raw

workflows:
  test:
    jobs:
      - test
